name: Continuous delivery

on:
  push:
    branches:
      - main            # CD roda aqui
  pull_request:
    branches:
      - '*'             # CI roda em qualquer branch

jobs:
  deliver:
    name: 📦 Build e Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Verificar arquivos
        run: ls -R

      - name: Upload do artifact
        uses: actions/upload-artifact@v4
        with:
          name: Projeto_zipado
          path: |
            **/*.py
            README.md

  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: deliver

    # 🔥 Só executa deploy na main (produção)
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download do artifact
        uses: actions/download-artifact@v4
        with:
          name: Projeto_zipado

      - name: Exibir arquivos
        run: ls -R